kind: pipeline
name: default

trigger:
  event:
    - push

steps:
- name: test
  image: golang:1.11
  commands:
  - go mod download
  - go build
  - go test

- name: "Build Docker image"
  image: plugins/docker
  settings:
    username:
      from_secret: quay_username
    password:
      from_secret: quay_password
    repo: quay.io/openware/wio
    tags: ${DRONE_COMMIT_SHA:0:7}
    registry: quay.io
